In [9]:
import kaggle

kaggle.api.authenticate()

kaggle.api.dataset_download_files('whisperingkahuna/serie-a-2324-team-and-player-insights', path='.', unzip=True)

Dataset URL: https://www.kaggle.com/datasets/whisperingkahuna/serie-a-2324-team-and-player-insights

In [28]:
# Import Libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import ast

# Loading Data
df_x = pd.read_csv('Serie A_table_xg_2023_24.csv')
df_big_chance = pd.read_csv('big_chance_team.csv')

# Data Clean up
#df_x.rename(columns={'name': 'Team'}, inplace=True)
#merged_df = pd.merge(df_x, df_big_chance, on='Team')

df_x

,idx,name,played,xg,xgConceded,xPoints,xgDiff,xgConcededDiff,pts
0,1,Inter,38,79.1526,31.4142,81.770904,9.8474,-9.4142,94
1,2,Juventus,38,55.8726,30.3752,70.235403,-1.8726,0.6248,71
2,3,Napoli,38,62.4344,39.2696,67.713537,-7.4344,8.7304,53
3,4,Milan,38,66.9867,46.3534,66.109611,9.0133,2.6466,75
4,5,Atalanta,38,58.7362,41.8656,63.097566,13.2638,0.1344,69
5,6,Roma,38,52.3391,42.3547,59.841562,12.6609,3.6453,63
6,7,Bologna,38,48.4763,37.4009,59.749251,5.5237,-5.4009,68
7,8,Fiorentina,38,52.9303,48.7953,56.317305,8.0697,-2.7953,60
8,9,Lazio,38,47.3601,43.2326,55.577535,1.6399,-4.2326,61
9,10,Torino,38,38.3742,37.7319,52.872503,-2.3742,-1.7319,53
10,11,Udinese,38,40.5411,49.6640,48.323760,-3.5411,3.3360,37
11,12,Genoa,38,36.3406,43.4279,45.626036,8.6594,1.5721,49
12,13,Lecce,38,43.9835,54.7583,44.322273,-11.9835,-0.7583,38
13,14,Hellas Verona,38,38.4802,49.2897,44.156123,-0.4802,1.7103,38
14,15,Frosinone,38,46.0496,59.4928,44.089054,-2.0496,9.5072,35
15,16,Cagliari,38,43.5202,55.2718,43.601563,-1.5202,12.7282,36
16,17,Monza,38,40.1966,56.9408,40.556915,-1.1966,-5.9408,45
17,18,Empoli,38,36.7509,54.3425,40.066971,-7.7509,-0.3425,36
18,19,Sassuolo,38,40.5833,62.3969,39.352546,2.4167,12.6031,30
19,20,Salernitana,38,30.6635,75.3939,23.963821,1.3365,5.6061,17

In [29]:
df_big_chance.reset_index()

    index  Rank           Team  Big Chances  Goals  Matches Country
0       0     1          Inter        121.0   89.0       38     ITA
1       1     2       Atalanta        100.0   72.0       38     ITA
2       2     3       AC Milan         98.0   76.0       38     ITA
3       3     4     SSC Napoli         94.0   55.0       38     ITA
4       4     5       Juventus         86.0   54.0       38     ITA
5       5     6           Roma         85.0   65.0       38     ITA
6       6     7     Fiorentina         81.0   61.0       38     ITA
7       7     8        Bologna         77.0   54.0       38     ITA
8       8     9          Lazio         71.0   49.0       38     ITA
9       9    10      Frosinone         71.0   44.0       38     ITA
10     10    11       Cagliari         67.0   42.0       38     ITA
11     11    12        Udinese         63.0   37.0       38     ITA
12     12    13          Monza         61.0   39.0       38     ITA
13     13    14          Lecce         61.0   32.0       38     ITA
14     14    15  Hellas Verona         57.0   38.0       38     ITA
15     15    16         Torino         57.0   36.0       38     ITA
16     16    17          Genoa         55.0   45.0       38     ITA
17     17    18       Sassuolo         52.0   43.0       38     ITA
18     18    19         Empoli         50.0   29.0       38     ITA
19     19    20    Salernitana         41.0   32.0       38     ITA